version: "3.8"
services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: good-things-user
      POSTGRES_PASSWORD: good-things-password0605
      POSTGRES_DB: good-things-db
    restart: always
    networks:
      - lesson
networks:
  lesson: